### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by hoang3402** [AnimeMoi/animemoireact#61]
- [x] Click vào thể loại ở detail sẽ chuyển ra home và tìm kiếm bằng thể loại
- [x] Click vào thể loại trên navbar sẽ tìm kiếm bằng thể loại [DONE] 
- [x] giữ tìm kiếm bằng thể loại và có thể chuyển sang page tiếp theo
- [x] tính năng chap tiếp, chap sau ở reader [DONE]
- [x] tìm kiếm chương ở detail -> chapter list [DONE] 
- [x] bấm vào đọc tiếp ở history [DONE]
- [x] update comic ở admin
- [x] hiển thị cái gì đó khi chapter rỗng [DONE]
- [x] tìm chương trong reader
